version: 2.1
orbs:  
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.5
  docker: circleci/docker@1.5.0
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/push-docker-image
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  build:
    executor: docker/default
    steps:
      - checkout
      - docker/build:
          image: $HEROKU_APP_NAME
workflows:
  lint-and-test:
    jobs:
      - lint
      - test
  publish:
    jobs:
      - build
      - heroku/push-docker-image:
          requires:
            - build
          filters:
            branches:
              only: main

