version: 2.1
orbs:  
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.5
  docker: circleci/docker@1.5.0
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/release-docker-image
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
  build:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: heroku login
      - heroku/push-docker-image
  whoami:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication:
          print-whoami: true
workflows:
  lint-and-test:
    jobs:
      - lint
      - test
  publish:
    jobs:
      - whoami
      - build
      - deploy:
          requires: 
            - build
          filters:
            branches:
              only: main

